### ISSUE TITLE
Meshlab shows exported mesh a triangle mesh?

### ISSUE THREAD

**Issue by embeh** [wjakob/instant-meshes#10]
Not sure this is an issue with instant-mesh or Meshlab, but exporting a remeshed result from instant-mesh as PLY or OBJ will produce a triangles-only mesh in Meshlab. The quad layout is preserved but all quads are triangulated.

**Comment by wjakob** [comment]
It's a display issue in Meshlab. You need to change the view settings so that it only shows non-"Faux" edges.

**Comment by embeh** [comment]
Thanks! 

Just in case someone else is having the same issue: You need to turn off the normal edge display (e.g switch back to Flat mode) in Meshlab and then enable Render > Show Non-Faux Edges from the main menu.

**Comment by raw915** [comment]
I have the latest version of MeshLab for the Mac and want to export a quad mesh. I don't see any way to "switch back to Flat mode" in MeshLab, and I don't see any "Render>Show Non-Faux Edges" option in the main menu. Any suggestions?
