### ISSUE TITLE
face distance

### ISSUE THREAD

**Issue by xarthurx** [wjakob/instant-meshes#101]
https://github.com/wjakob/instant-meshes/blob/011fa44ab72037cbc16535090a63ead41963c1e5/src/smoothcurve.cpp#L166

Should this line be:
```
            diff += V.col(F(k, i)) - V.col(F(k, j));
```
?

Otherwise, the accumulation of 3 length doesn't seem to take effect.

The original code overwrites the `diff` at each iteration.

**Comment by wjakob** [comment]
Indeed, that is clearly a typo -- thanks!
