### ISSUE TITLE
Failure to import georeferenced mesh

### ISSUE THREAD

**Issue by Jean-Roc** [wjakob/instant-meshes#11]
Hello,

I've tried to import a georeferenced mesh (*.obj) in your software but it crashes during the import step with this error ([full log](https://github.com/wjakob/instant-meshes/files/37690/NativeCommandError.txt) - [source file](https://drive.google.com/open?id=0B1sJg8zddqSPRHFoMWJtWDBsenc)) :
>  + CategoryInfo : NotSpecified: (Caught exceptio... bad allocation:String) [], RemoteException
>  + FullyQualifiedErrorId : NativeCommandError

Is the coordinate space used too big for Instant Mesh ?

**Comment by wjakob** [comment]
This mesh is clearly corrupted -- try looking at it in meshlab ;).

Instant meshes runs out of memory while trying to suvdivide it to uniform density, which is not a surprise in this case.
