### ISSUE TITLE
How to open point cloud .PLY file?

### ISSUE THREAD

**Issue by nvibd** [wjakob/instant-meshes#127]
What format is expected so that a point cloud as .PLY file can be opened?

We have some point clouds in .PLY format, however when trying to open them with Instant Meshes, the error "PLY file [...] is invalid! No faces found!" is shown.

**Comment by Rhysjosmin** [comment]
first try making them into a mesh
 https://youtu.be/GEAbXYDzUjU?t=450

then export them with the obj file format

**Comment by nvibd** [comment]
I don't want to run Screened Poisson Surface Reconstruction on the point cloud -- I know that exists in separate software. I specifically want to mesh using the published algorithm of "Instant Meshes":

"In this section, we propose a simple and efficient way of turning the computed fields into a mesh, which works for 4-and 6-PoSy fields and can handle point clouds."

They also show it in the video here: https://youtu.be/U6wtw6W4x3I?t=158

**Comment by nvibd** [comment]
I got it working by flipping this `false` to `true`, here: https://github.com/wjakob/instant-meshes/blob/7b3160864a2e1025af498c84cfed91cbfb613698/src/meshio.cpp#L33

**Comment by iszihan** [comment]
May I ask how did you input the computed field information on the point cloud?
