### ISSUE TITLE
Could not initialize GLFW

### ISSUE THREAD

**Issue by undeadBryce** [wjakob/instant-meshes#13]
When launching the Windows binary I get this error:

"Caught a fatal error: Could not initialize GLFW"

The console output says:

"Running in GI mode, start with -h for instructions on batch mode.\nGLFW error 65544: No monitors found"

Possibly helpful/relevant: I'm running Windows 10 with a GTX 760 on drivers 359.00

![image](https://cloud.githubusercontent.com/assets/8700069/11278943/7959f718-8ea2-11e5-8c5f-71db3b6bda63.png)

**Comment by undeadBryce** [comment]
I solved this problem by going to the Device Manager -> Monitors  -> Update Driver Software... on each of my monitors. They were originally labeled as PnP Monitors and after updating they changed to the actual monitor brand/make.

![image](https://cloud.githubusercontent.com/assets/8700069/11279415/5841b0ae-8ea5-11e5-8e15-67ab2e190de2.png)

**Comment by ROIAF** [comment]
I'm still getting this even after updating my monitor drivers.  Do you have any other ideas?

![image](https://cloud.githubusercontent.com/assets/13202838/13030930/54bc67ea-d26f-11e5-903d-a36e43d5ce13.png)
