### ISSUE TITLE
Question: Standalone Library?

### ISSUE THREAD

**Issue by crydalch** [wjakob/instant-meshes#15]
Wonderful you guys, thanks for sharing your research in such an accessible way!

I was wondering if there's a way to build a standalone library for this functionality? That'd make it easier to include the tools in other programs, or even wrap it in a Python library.

Would that be a ton of work, or is a lot of the groundwork already there?

Cheers!

**Comment by wjakob** [comment]
It would be easy to do, for instance using my pybind11 project (https://github.com/wjakob/pybind11). You'll have to invest a bit of work though.

**Comment by crydalch** [comment]
Thanks @wjakob for the pybind11 tip! Very cool project!
