### ISSUE TITLE
GLFW error 65544: No monitors found, Win10 64bit

### ISSUE THREAD

**Issue by loadingx86** [wjakob/instant-meshes#16]
When executing "Instant Meshes.exe"
![Error](http://i.imgur.com/lZfiG3L.jpg)

**Comment by wjakob** [comment]
Duplicate of #3 and #13.

**Comment by emile58** [comment]
Bonjour.

Excusez mois, mois aussi j'ai ce problème avec instant meshes.exe ? 
![Erreur 65543](https://user-images.githubusercontent.com/49947658/56660163-39f98d80-669f-11e9-9de2-a031051ec4b8.PNG)
