### ISSUE TITLE
Keep boundary edges and only change internal topology?

### ISSUE THREAD

**Issue by sambuev** [wjakob/instant-meshes#17]
Hi, this is great software, can you please add boundary edges option? Let's say I have a cube and when I retopo this cube edges on this cube doesn't look straight anymore and cube can look like a sphere after retopo, it would be good to have "Force to keep boundary edges" option while retopo.

Thank you.

**Comment by wjakob** [comment]
Hi -- it's a good suggestion but beyond the scope of this project. This repository serves as the reference implementation of an academic paper, and there it's not planned to add significant additional functionality (other than fixing bugs etc.). The source code is available, so anyone can fork and make modifications though.
-Wenzel
