### ISSUE TITLE
Build in windows

### ISSUE THREAD

**Issue by changjianli** [wjakob/instant-meshes#18]
Hi Wenzel,

I like the great software, but I have errors when building in windows. Does it need the Nano-GUI or libgl precompiled?

Look forward to your reply!

Best,
Changjian

**Comment by wjakob** [comment]
If you follow the build instructions (clone with --recursive, compile with visual studio 2015), it should automatically build all dependencies.
Otherwise, can you provide a few more details? (other than that there are errors)

**Comment by changjianli** [comment]
How about visual studio 2012?

**Comment by wjakob** [comment]
Sorry, it's not supported.

**Comment by wjakob** [comment]
Visual studio 2015 is freely available (community edition) -- just download it here: https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx

**Comment by changjianli** [comment]
Thanks a lot, I will try.
