### ISSUE TITLE
Zoom extents/view mesh

### ISSUE THREAD

**Issue by goduran** [wjakob/instant-meshes#19]
I have a georeferenced mesh that I've worked on in Meshlab (about 2 million points). when I open it in Instant Meshes, I get no error messages, everything seems to have worked, but there's nothing visible in the viewport. I'm not sure if it's because the mesh is located at coordinates that would be far from 0,0 or some other issue.

**Comment by wjakob** [comment]
Probably the issue is that the software imported your mesh as geometry and not a point cloud. Are you using the PLY format? Note also that you'll have to specify per vertex normals for Instant Meshes to be able to process your data.
