### ISSUE TITLE
topology flow

### ISSUE THREAD

**Issue by mirlip** [wjakob/instant-meshes#2]
Hi Wenzel,
Nice to see you on a new project. First tests look really promising. You can follow a pretty active discussion here http://blenderartists.org/forum/showthread.php?385344-Instant-field-aligned-meshes (2 pages in one day). Some test over there show that the topology flow analysis could be improved. Zremesher for example offers better results "out of the box". Maybe there are some way to improve this in instant meshes? Many of us will be happy to help test and give files and feedback.
Thank you for sharing high quality product again with us. I hope you also find some time to finish a release of mitsuba with all the latest improvements.
Regards,
mirlip

**Comment by wjakob** [comment]
Dear mirlip,

we saw the thread and were happy to see some excitement. Regarding the Zremesher vs IFAM comparison: the fundamental tradeoff of our technique is that it introduces more singularities to obtain higher isotropy. Thus it is not primarily targeted at the traditional "retopo" workflow where users want very coarse pure quad meshes (though we're interested in extensions that provide more control in this regard in the future).

Best,
Wenzel

**Comment by wjakob** [comment]
Closing this ticket since it's not a fixable issue for now.

**Comment by mirlip** [comment]
Thanks for the answer Wenzel. I can understand your point. Viel Spass bei der weitere Bearbeitung.
