### ISSUE TITLE
Could not initialize GLFW

### ISSUE THREAD

**Issue by ROIAF** [wjakob/instant-meshes#21]
Just tried to use for the first time after downloading and when the window opens, it gives a "GLFW error 65544: No monitors found" error.  The error box pops up with Caught a fatal error: Could not initialize GLFW!

Any suggestions?

**Comment by wjakob** [comment]
Duplicate of #13.

**Comment by wjakob** [comment]
Either way, this is a configuration issue with GLFW (http://www.glfw.org/) in your issue and not at all related to Instant Meshes. It's not something that can be solved here.
