### ISSUE TITLE
Spline (or bezier curves) as brushes (feature request)

### ISSUE THREAD

**Issue by ssh4net** [wjakob/instant-meshes#25]
First of all biggest thanx for this amazing open-source app!

After playing with your app. Found that not so easy draw guide (brushes) with mouse.
All commercial retopo tools provide **spline drawing** for similar task. So may be possible, add this feature to new version of instant-meshes?

Thank you,
And best regards

**Comment by wjakob** [comment]
This project is provided "as is", and we sadly don't have the resources to implement features requests such as this one. If you wish to implement this and submit a PR, then I would be interested. I am closing this ticket, since there is no issue/bug.
