### ISSUE TITLE
Support for adaptive mesh generation

### ISSUE THREAD

**Issue by rpopovici** [wjakob/instant-meshes#26]
Hello @wjakob 

I have seen in your published paper that you talk about custom metrics(figure 22) I am wondering if this is possible with the current implementation of this tool. I am interested more in mean curvature support.
It makes sense for organic meshes if you want to generate a very low poly topology. Thanks!

**Comment by wjakob** [comment]
Hi @rpopovici,

it's not possible with the current code, but this feature is fairly straighforward to integrate. I can send you a patch if you are interested. The reason why we never did it here is because this requires heavy modifications of the user interface.

Best,
Wenzel

**Comment by andmurzaev** [comment]
Hello
I am also interested in custom metrics usage based on the mean curvature. I tried to variate edge length for vertices with different curvature value. But it looks like I do something wrong because most of meshes I tested look very bad. 
Can you send me a patch or share idea of custom metrics usage?
Thanks!

**Comment by DMartinek** [comment]
Hi,
has anyone had any success in implementing adaptiv meshes based on curvature? I'm currently analyzing the code and trying to find out where exactly to modify it. It would be great and save me a lot of time if someone could nudge me in the right direction.

Greetings,
Daniel

**Comment by naikjoy** [comment]
Hi @wjakob 
Could you send me that patch too?

**Comment by wjakob** [comment]
Here it is -- please note that this was from a long time ago (before the paper was published) and won't directly apply to the current source release. If somebody here puts in the time to get this to merge again, an updated patch would be greatly appreciated.

[scale-adaptive.txt](https://github.com/wjakob/instant-meshes/files/2199544/scale-adaptive.txt)

**Comment by naikjoy** [comment]
Thank you very much.
I'm a bit of a newbie tho and I don't know how to code or merge this. 
Anyone willing to help a poor guy out?

Btw @wjakob Thank you so very much for this piece of software!
It helps me a lot to realize my dream of making my own racing game with my province in it.
![Showcase](https://user-images.githubusercontent.com/41309172/42985630-9e0e4424-8bf2-11e8-9a69-e68b83219610.png)
