### ISSUE TITLE
would it be possible to make a build for older glibc on Linux?

### ISSUE THREAD

**Issue by samhodge** [wjakob/instant-meshes#27]
Currently there is a dependency on C++11 which brings in a dependency on a later glibc than is available in CentOS 6.2 which is what we are currently locked into in my place of employment.

Would it be possible to negate the need for this?

That being said it compiled without a hitch on OSX 10.11 at home.

**Comment by wjakob** [comment]
Sadly it will be hard to do this with travis -- for Linux, I assume that it will be easy enough for folks to compile this on their own though.
