### ISSUE TITLE
maya style view navigation?

### ISSUE THREAD

**Issue by 3dthomas** [wjakob/instant-meshes#28]
would it be possible to implement a maya-style view navigation? it is enough of an industry standard that most 3D folk should be very familiar with it. it is also very tablet friendly - and tablet is best for drawing the guides in instant meshes.

**Comment by wjakob** [comment]
This project is provided "as is", and we sadly don't have the resources to implement features requests such as this one. If you wish to implement this and submit a PR, then I would be interested. I am closing this ticket, since there is no issue/bug.
