### ISSUE TITLE
Could not initialize GLFW

### ISSUE THREAD

**Issue by DFin** [wjakob/instant-meshes#3]
When running the compiled version of it i get above error. (using Win 10 btw).

**Comment by wjakob** [comment]
... which is? :)

**Comment by DFin** [comment]
the headline: Could not initialize GLFW

**Comment by wjakob** [comment]
ah, in the title -- ok. Your graphics card does not support OpenGL 3.x in this case then. Maybe on a different machine or with more recent drivers?

I am closing this issue since it is definitely not related to this project.

**Comment by DFin** [comment]
It is not graphic card or driver related. I use a FirePro W9100 that has OpenGL 4.3/4.4 support and most recent drivers.

**Comment by wjakob** [comment]
That is pretty surprising then -- Instant Meshes does nothing special here other than calling the GLFW initialization code. Can you run other GLFW projects? (http://www.glfw.org/)

**Comment by DFin** [comment]
I just tested OpenGL functionality and a precompiled GLFW project and I didn't have any issues. Are there any specific runtimes needed of instant meshes?

**Comment by wjakob** [comment]
Ok, so I just made a minor change that will probably not fix the issue on your end. But it might provide a more helpful error message -- can you download the latest .exe file and try again?

**Comment by DFin** [comment]
GLFW error 65544: No monitor found.

Sorry, I now found the issue on my end. The monitor was disabled in the Device Manager. It still worked fine in windows, because its the only monitor currently attached, but caused the issue on GLFW. The issue is gone since I enabled the monitor again. So that error message really helped. Thank you and sorry for the inconvenience.

**Comment by wjakob** [comment]
ok, good to hear that the error message helped.
