### ISSUE TITLE
Crash when increasing target vertex count

### ISSUE THREAD

**Issue by carlvieriste** [wjakob/instant-meshes#30]
##### Using build: Visual Studio 2015 / Win32 / RelWithDebInfo
1. Load [this mesh](https://drive.google.com/file/d/0B2yDwuHAZNzJbUlCdGhmQTFDMUE/view?usp=sharing). Notice that Target vertex count is: **60.12K**;
2. Increase Target vertex count to >100K (**110.05K** to be precise);
3. Wait for a few seconds as the program loads and processes the mesh.

## Result
Instant Meshes crashes. Visual studio shows this dialog:

> Unhandled exception at 0x00F8801E in Instant Meshes.exe: Fatal program exit requested.

Console window shows:

> Caught exception in event handler: bad allocation

**Notes:**
* Computer does not run out of memory.
* Why is there no 64bit configuration in the `.sln`?

## Call stack

```
Instant Meshes.exe!abort() Line 77	C++
Instant Meshes.exe!nanogui::Screen::mouseButtonCallbackEvent(int button, int action, int modifiers) Line 500	C++
Instant Meshes.exe!<lambda_d39877562765bc0d3052e6c01bd928d1>::<lambda_invoker_cdecl>(GLFWwindow * w, int button, int action, int modifiers) Line 166	C++
Instant Meshes.exe!_glfwInputMouseClick(_GLFWwindow * window, int button, int action, int mods) Line 192	C
Instant Meshes.exe!windowProc(HWND__ * hWnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 438	C
[External Code]	
[Frames below may be incorrect and/or missing, no symbols loaded for user32.dll]	
Instant Meshes.exe!_glfwPlatformPollEvents() Line 995	C
Instant Meshes.exe!nanogui::mainloop(int refresh) Line 102	C++
Instant Meshes.exe!main(int argc, char * * argv) Line 213	C++
[External Code]	
```

**Comment by wjakob** [comment]
Can you try with a 64 bit build? You'll need to run cmake-gui and select the 64 bit project generator for this to work.

**Comment by wjakob** [comment]
Closing since there was no feedback. Feel free to reopen if you still have issues with a 64 bit build.
