### ISSUE TITLE
Error while compiling on Arch Linux

### ISSUE THREAD

**Issue by RastaManKing** [wjakob/instant-meshes#32]
:   required from here
/home/rastamanking/Portables/instant meshes LINUX/instant-meshes/ext/nanogui/ext/eigen/Eigen/src/Core/DenseCoeffsBase.h:56:30: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<float>::type {aka __vector(4) float}’ [-Wignored-attributes]
make[1]: *** [CMakeFiles/Makefile2:70: CMakeFiles/InstantMeshes.dir/all] Error 2
make: *** [Makefile:128: all] Error 2

when running "make -j 4"

**Comment by stephane-lb** [comment]
Hi @RastaManKing,

I compiled it on Archlinux months ago ( even if it was a VM ) do you have more details please ?

Thanks,

Stephane

**Comment by stephansturges** [comment]
Hey,
I dont think this message was for me...? I posted a question about not
having the "point cloud" as an input option in the gui 😊
Although actually I'm running the software in command line mode, is there a
way to feed it a point cloud there ?

Cheers,
Stephan

**Comment by wjakob** [comment]
The OP only reports a warning no error -- closing this ticket .
