### ISSUE TITLE
batch process

### ISSUE THREAD

**Issue by ardworx** [wjakob/instant-meshes#35]
Hi,
Awesome Product! 
As I have a lot of meshes that all need the exact same treatment, (just set the target vertex count to 200K and solve/export it).
I would like to know if there is a way to tell instance mesh to do that per command line.
Is that already possible? 
Thanks in advance!

**Comment by wjakob** [comment]
Yes, it is. Call the binary with -h.

**Comment by ardworx** [comment]
Thank you!
