### ISSUE TITLE
Not starting up on Windows 7

### ISSUE THREAD

**Issue by Amnesi4c** [wjakob/instant-meshes#36]
I get this error whenever I try to start it on windows:

Running in GUI mode, start with -h for instructions on batch mode.
Compiling shaders .. Linker error (mesh_shader_63):
Geometry info
-------------
0(28) : warning C7050: "frag.to_eye" might be used before being initialized
0(28) : warning C7050: "frag.to_light" might be used before being initialized
0(28) : warning C7050: "frag.texcoord" might be used before being initialized
0(28) : warning C7050: "frag.color" might be used before being initialized

Link info
---------
error: type mismatch for varying parameter (named fData.to_eye) between shader s
tages
error: type mismatch for varying parameter (named fData.to_light) bet

**Comment by wjakob** [comment]
Hi @Amnesi4c,

I fear that this is a graphics card driver. The warning messages don't make any sense -- for instance, ``fData.to_eye`` does not have different types between shader stages.

Out of curiosity: what kind of graphics card are you using?

Best,
Wenzel
