### ISSUE TITLE
Build issue on linux

### ISSUE THREAD

**Issue by doakey3** [wjakob/instant-meshes#37]
When I tried to build the program on linux, the terminal puts out an error and fails:
   ```
/instant_meshes/src/common.h:97:27: error: exponent has no digits
#define RCPOVERFLOW_FLT    0x1p-128f
```
I googled this and found that by changing the line 
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`
to 
 `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11")`
in the CMakeLists.txt, I was able to get the program to build successfully.

Also, I figured out that installing [zenity](https://help.gnome.org/users/zenity/stable/) is required for making some parts of your GUI work, but it wasn't mentioned in your README.

**Comment by wjakob** [comment]
(I also added a note to the README about zenity)
