### ISSUE TITLE
unlisted/unincluded dependencies

### ISSUE THREAD

**Issue by rviertel2** [wjakob/instant-meshes#38]
In order to build Instant Meshes on Ubuntu 16.04 I had to install the following packages:

libxrand-dev
libxinerama-dev
xcursor-dev
libxi-dev

I was warned that I needed the first 3 when running cmake but the last one not until the build failed.

**Comment by wjakob** [comment]
These warnings are part of GLFW, so it's out of my hands. I will add a note to the README though.
