### ISSUE TITLE
Please recheck the linux dependency notes in the README file

### ISSUE THREAD

**Issue by Robert42** [wjakob/instant-meshes#40]
On Linux Mint 18 (uses same repositories like Ubuntu 16.06 for which I assume the instructions were made):
- There's no `libxrand-dev` package, but a `libxrandr-dev`
- There's no `xcursor-dev` package, but a `libxcursor-dev`

The other packages from this [README section](https://github.com/wjakob/instant-meshes/blob/37603748710e0d5bd211a5785c170a67cec4ce8b/README.md#compiling) do exist for Linux Mint 18

**Comment by wjakob** [comment]
Fixed, thanks.

**Comment by Robert42** [comment]
You're welcome :D
