### ISSUE TITLE
Export building oversized files seemingly forever

### ISSUE THREAD

**Issue by JurajTalcik** [wjakob/instant-meshes#41]
Hi there,

first of all, incredible tool. I found it when looking for retopo tool that can go above the conventional limit of other tools (Zremesher=100k poly), since I need to retain detail of complicated photoscanned meshes bit better.
It loads my files well, it's super fast ( 60 million poly mesh loads for few minutes but then retopos under single minute on my dual-xeon/titan-x;  decimated 10 mil poly mesh takes the whole process in mere seconds...).
Everything goes well until I try to export anything else then the data sets that come with it. It builds large .obj files forever. I've noticed some people reported that on youtube and reply it could be fixed, but I downloaded the latest binary today (Windows 10, 64bit).

Example of mesh I am processing.

I have the feeling the issue might be a bit in the dirtyness of the files, they end up with lot of irregularities, but sadly this is how the files are created by RealityCapturePro, state of art tool for photogrammetry (it creates meshes directly, not dense pointclouds, so can't try that option). Due to their size it's almost impossible to clean them even in Meshlab so I am suprised how well this tool handles it. Until that export :- ).

If possible, I have private WeTransfer link I can send to email ( it's rather large files but again, it's processed incredibly swiftly).

This tool is almost dream come true, would be great if this could be possible to be solved.

Thank you,

Juraj
talcikdemovicova.com

![bed](https://cloud.githubusercontent.com/assets/23201478/19910775/68136eb2-a08f-11e6-9557-07350065e771.jpg)

**Comment by wjakob** [comment]
@JurajTalcik: There is a pending patch for this issue which would be good to verify -- can you email me a link to one of those files? (wenzel.jakob@epfl.ch)

**Comment by JurajTalcik** [comment]
Thank you for swift reply Jakob ! Sent you an email with WeTransfer link.

**Comment by wjakob** [comment]
This is fixed now.
