### ISSUE TITLE
GPU init failure

### ISSUE THREAD

**Issue by dokunod** [wjakob/instant-meshes#42]
I start instant meshes on remote server, and there is 4 graphics adapters, so, because of remote server connection , the first adapter in a row is Microsoft Basic Video Adapted, and it has no OpenGL, but there is another GPU in a sytem Nvidia GTX 960, it has a proper OpenGL version and works fine with other software in a system, but Instant-Meshes could not see this GPU, and does not start because of it. Could you please implement some  tweak to be able to choose which GPU to use, or at least give your software a possibility to look for another GPU in a system, not only first one in a list ? Please help !!

**Comment by wjakob** [comment]
Running instant meshes (and generally complex OpenGL programs) remotely does not work on Windows machines -- it's not something specific to Instant Meshes.
