### ISSUE TITLE
Mesh isn't showing(Windows Build)

### ISSUE THREAD

**Issue by AFWSI** [wjakob/instant-meshes#44]
I just downloaded the windows build. When I try to open a mesh it says it has been opened and all the functions at like the mesh is there ,but the mesh isn't visible. Don't think it's something with my computer, cause other 3D programs work fine ,but can't determine the cause since there is just one version to download.

**Comment by wjakob** [comment]
What graphics card are you using? I suspect an issue with a builtin graphics card with poor driver support (e.g. Intel).

**Comment by AFWSI** [comment]
See if this is what you needing.     CPU = Intel(R) Core (TM) i7-6700 HQ 2.60 GHz , GPU= NVIDIA GeForce GTX 950m

**Comment by AFWSI** [comment]
It seems to be working now. I updated graphics driver and told it to use integrated graphics, instead of high performance graphics. Not sure which did the trick.

**Comment by wjakob** [comment]
The latter I think.
