### ISSUE TITLE
Compliation failed!

### ISSUE THREAD

**Issue by CyberPaddy66** [wjakob/instant-meshes#46]
I followed the instructions for making sure that the packages and datasets are in the correct place but when I try to compile the program it falls over with the following response...

[code]cp66@cp66-desktop:~/instant-meshes$ make -j 4
[  2%] Built target bin2c
Scanning dependencies of target tbb_static
[ 15%] Built target glfw_objects
[ 16%] Built target glfw
[ 16%] Building CXX object ext_build/nanogui/CMakeFiles/nanogui-obj.dir/src/common.cpp.o
[ 17%] Building CXX object ext_build/nanogui/CMakeFiles/nanogui-obj.dir/src/glutil.cpp.o
[ 18%] Building CXX object ext_build/nanogui/CMakeFiles/nanogui-obj.dir/src/widget.cpp.o
[ 19%] Building CXX object ext_build/tbb/CMakeFiles/tbb_static.dir/src/tbb/tbb_misc.cpp.o
**In file included from /home/cp66/instant-meshes/ext/nanogui/include/nanogui/opengl.h:34:0,
                 from /home/cp66/instant-meshes/ext/nanogui/src/common.cpp:18:
/home/cp66/instant-meshes/ext/nanogui/ext/glfw/include/GLFW/glfw3.h:168:21: fatal error: GL/gl.h: No such file or directory
compilation terminated.
ext_build/nanogui/CMakeFiles/nanogui-obj.dir/build.make:144: recipe for target 'ext_build/nanogui/CMakeFiles/nanogui-obj.dir/src/common.cpp.o' failed
make[2]: *** [ext_build/nanogui/CMakeFiles/nanogui-obj.dir/src/common.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/cp66/instant-meshes/ext/nanogui/include/nanogui/opengl.h:34:0,
                 from /home/cp66/instant-meshes/ext/nanogui/include/nanogui/glutil.h:15,
                 from /home/cp66/instant-meshes/ext/nanogui/src/glutil.cpp:12:
/home/cp66/instant-meshes/ext/nanogui/ext/glfw/include/GLFW/glfw3.h:168:21: fatal error: GL/gl.h: No such file or directory
compilation terminated.
ext_build/nanogui/CMakeFiles/nanogui-obj.dir/build.make:120: recipe for target 'ext_build/nanogui/CMakeFiles/nanogui-obj.dir/src/glutil.cpp.o' failed
make[2]: *** [ext_build/nanogui/CMakeFiles/nanogui-obj.dir/src/glutil.cpp.o] Error 1
In file included from /home/cp66/instant-meshes/ext/nanogui/include/nanogui/opengl.h:34:0,
                 from /home/cp66/instant-meshes/ext/nanogui/src/widget.cpp:16:
/home/cp66/instant-meshes/ext/nanogui/ext/glfw/include/GLFW/glfw3.h:168:21: fatal error: GL/gl.h: No such file or directory
compilation terminated.
ext_build/nanogui/CMakeFiles/nanogui-obj.dir/build.make:168: recipe for target 'ext_build/nanogui/CMakeFiles/nanogui-obj.dir/src/widget.cpp.o' failed
make[2]: *** [ext_build/nanogui/CMakeFiles/nanogui-obj.dir/src/widget.cpp.o] Error 1
CMakeFiles/Makefile2:130: recipe for target 'ext_build/nanogui/CMakeFiles/nanogui-obj.dir/all' failed
make[1]: *** [ext_build/nanogui/CMakeFiles/nanogui-obj.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 20%] Linking CXX static library libtbb_static.a
[ 53%] Built target tbb_static
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2**
[/code]

I am running an Ubuntu 16.10 PC that is fully up to date and I have triple checked that the file glfw3.h that results in the first error is indeed there so I don't know what I can do to get this program working, please help me!

**Comment by rviertel2** [comment]
you probably don't have OpenGL installed.  Check if you have gl.h in /usr/include/GL

**Comment by CyberPaddy66** [comment]
Indeed I don't, thanks for that tip I will get it installed after the weekend.
