### ISSUE TITLE
Opportunity - Point Cloud import from laserscans?

### ISSUE THREAD

**Issue by GaryKT** [wjakob/instant-meshes#47]
Hi,

Have you considered importing point clouds directly? Is that something you could support?
E.g. import E57 files.

We need to mesh laserscan data with a clean topology and most meshing tools out there do not create clean meshes. We currently would need to
a) use meshing software to convert point cloud to mesh
b) export mesh to OBJ
c) instant-meshes coverts mesh to point cloud to create clean topology
d) export mesh to OBJ

Maybe you could use the point cloud straight out. There is also some opportunity around texturing.

**Comment by wjakob** [comment]
Hi @GaryKT,

this is definitely possible to add, but you would have to implement this feature yourself. Unfortunately our resources are very constrained, and we thus rely on outside contributions for feature requests.

Best,
Wenzel
