### ISSUE TITLE
high GPU usage in windows

### ISSUE THREAD

**Issue by mirlip** [wjakob/instant-meshes#5]
Hi Wenzel,
When I use Instant mesh on a laptop, it draws my battery to 5% in 30minutes. At home, I monitored with GPU-Z on a 280X under windows. It shows that instant mesh uses 80% CPU just by moving the mouse over the GUI. It happens with or without any data loaded.
Configuration: Win 7 x64, AMD R9 280X, latest Catalyst (15.11), GPUZ 0.8.6
Regards

**Comment by wjakob** [comment]
Not sure what to do about this bug report: the issue does not occur on NVidia cards, and I don't have access to AMD hardware. Does the same issue occur for you when running on the NanoGUI examples?

Can you profile/benchmark the GPU usage and perhaps track it down to a more specific shader? As is, this ticket does not contain enough information to make it actionable.

**Comment by HeadClot** [comment]
@wjakob - I can do some bench marking if needs be just tell me what info you need :)

I am on an AMD R7 265. :)

- Benjamin

**Comment by wjakob** [comment]
You'd need to run the application with some kind of ATI-specific debugger that lets you track down CPU usage to specific lines in the shader. I assume that something like that exists, but must admit that I'm not at all familiar with ATI development software.

**Comment by mirlip** [comment]
It's GPU usage, not CPU. Just run GPU-Z while moving your mouse over the instant-meshes window. You don't need to open a mesh, just start the program and mouse hover the window while monitoring with GPU-Z. I tested on Intel GPU, same behavior. Using V-Sync reduces the usage (certainly because it's then limited to 60 refresh per second). Even when not moving the mouse, I get some usage spikes. For comparison, Blender or Vectorworks let the GPU idle when not used.

**Comment by wjakob** [comment]
I am closing this ticket -- it's missing sufficient technical information to turn it into something actionable.
