### ISSUE TITLE
License says something silly

### ISSUE THREAD

**Issue by zewt** [wjakob/instant-meshes#51]
The license contains a nonstandard clause, containing this text:

"then you hereby grant the following license:"

This clause doesn't make any sense.  You can't cause somebody else to grant a license by declaring that they've done so, any more than I can cause you to buy me a pizza by saying "by replying to this bug report you hereby agree to buy me a pizza".  I'd suggest sticking to the standard BSD license that thousands of projects use, and not making ad-hoc changes to it.

(This is feedback rather than a bug report, but unfortunately GitHub gives users no way of communicating with projects other than filing bugs.)

**Comment by wjakob** [comment]
This addition is actually extremely common -- if you google for the text, you will find it in many other projects using the BSD license. It does not affect the licensing of the software itself and just clarifies how external contributions are licensed (which is fairly obvious: under the same conditions). In other words: it's a lightweight version of a CLA.
