### ISSUE TITLE
 Objects with thin clothes have holes

### ISSUE THREAD

**Issue by newpolaris** [wjakob/instant-meshes#55]
The thick part of the object is successfully converted. However, thin clothes seem to have holes. Is this an algorithmic problem? How can I solve this problem?

[File](https://www.dropbox.com/s/pf99oqwd1a1oteb/mikudayo-3_6_.ply?dl=0)

![2017-08-24_17-56-18](https://user-images.githubusercontent.com/4484556/29658683-c3390888-88f6-11e7-9b95-9c582ad956a2.png)
![2017-08-24_17-55-52](https://user-images.githubusercontent.com/4484556/29658693-c7afcfa0-88f6-11e7-8206-c1ab8eb17bb7.png)

**Comment by wjakob** [comment]
Hi @newpolaris,

the feature size you have chosen is much too low for the given model, it is expected that IM will fail under such circumstances. 

Best,
Wenzel
