### ISSUE TITLE
What should i do with the msg: input mesh is too coarse for the desired output edge length ?

### ISSUE THREAD

**Issue by alvaro562003** [wjakob/instant-meshes#56]
Hello,
I am learning how to use "instant-meshes" on the command line.

Whenever, i launch this command :
`"Instant Meshes.exe" "MyModel.ply" -o "final.obj"  --faces "100000"`
i get this message:

> Input mesh is too coarse for the desired output edge length (max input mesh edge length=0.0082588), subdividing ..

What does it mean ? and what should i do to success in reducing the number of faces ?

Thank you

**Comment by wjakob** [comment]
Hi @alvaro562003,
there is no reason to concern. Instant Meshes just needs a sufficient mesh resolution to do its job (i.e. for intermediate steps of the computation). The output will still reflect your wishes with regards to the ``--faces`` parameter.

**Comment by alvaro562003** [comment]
thank you
