### ISSUE TITLE
how to remove the wireframe colore

### ISSUE THREAD

**Issue by guzuomuse** [wjakob/instant-meshes#57]
@wjakob ,thanks for this great tool!!!!
here is a "problem" when import the obj file generated by instant-meshes tool into blender software.
when in edit-mode,there have the wireframe colored. how to remove the wireframe's color. thanks!
![_2017_09_21_14_16_07_865](https://user-images.githubusercontent.com/5040829/30681525-6005f490-9ed8-11e7-97fc-c9959dfbd707.png)
and it should be like this:
![_2017_09_21_14_17_32_556](https://user-images.githubusercontent.com/5040829/30681533-6cd07114-9ed8-11e7-9773-5e2a1050f81f.png)

**Comment by wjakob** [comment]
Sorry, not sure what this is referring to. Unfortunately we can't support Blender or similar software here, the bug tracker is only for issues with IM itself.
