### ISSUE TITLE
Other TBB version

### ISSUE THREAD

**Issue by bamfbamf** [wjakob/instant-meshes#59]
I'm planning to make full C++ integration of your plugin with Houdini application.

Houdini is already using TBB, but different version. It seems it's stuck on `Intel TBB 4.4 Update 6 TBB_INTERFACE_VERSION == 9006`, while Instant Meshes seems to use `Intel TBB 2017 TBB_INTERFACE_VERSION == 9100`. That's only one version higher, according to https://www.threadingbuildingblocks.org/sites/default/files/resources/CHANGES.txt, but I know from experience that Houdini doesn't like any other TBB libraries beside its own. Otherwise crashes and other strange things can happen. This is note from their docs:
`Houdini is built with special custom allocator libraries that override the default allocation routines (eg. malloc, free, etc.). As such any code you build or link into HDK plugins cannot use their own such libraries such as tbbmalloc_proxy. If you do, then conflicts and crashes can occur as a result. `

Would there be big problem with replacing TBB that comes with InstantMeshes with the one coming with Houdini? Do you use any changes from this new version?

**Comment by wjakob** [comment]
The TBB version should not matter particularly.
