### ISSUE TITLE
Hi-Dpi Support?

### ISSUE THREAD

**Issue by BellaCoola** [wjakob/instant-meshes#64]
Hello friends,

When I try to run Instant Meshes on Linux on Hi-Dpi monitor its GUI is so small that it is nearly unusable :(

I enclose a screenshot of my problem:

![instant_meshes_problem](https://user-images.githubusercontent.com/31868524/33170974-98d6929a-d04a-11e7-8710-43aa014a29ea.png)

Please do you know of some way how to make it bigger? Maybe adding some cmdline flag when starting the application? Or is there some option inside the application to make the GUI bigger?

Thank you very much and have a nice day.

**Comment by wjakob** [comment]
Should be fixed in the latest version.

**Comment by juxi500** [comment]
Thank you very much, where can we find the latest version?
