### ISSUE TITLE
When Pure quad mesh is ON, the extracted faces are weird

### ISSUE THREAD

**Issue by cristiprefac** [wjakob/instant-meshes#67]
If the Pure quad mesh option is active, there seem to be some kind of overlapping faces after extracting the mesh. It does that in the application but also when used as an external library.
![image](https://user-images.githubusercontent.com/419728/35329190-8c787c8c-0107-11e8-8573-296b7312c8ea.png)

**Comment by wjakob** [comment]
It works fine here -- perhaps an issue with this specific mesh?

**Comment by wjakob** [comment]
Thanks for the report, that was a regression introduced in 4a083f45735c188b4107837e0bda00f6d8c0abb6, now fixed in 011fa44ab72037cbc16535090a63ead41963c1e5.
