### ISSUE TITLE
License info button and output attribution

### ISSUE THREAD

**Issue by AndreaMonzini** [wjakob/instant-meshes#76]
Hello, 
 i'm testing istant-meshes on Linux and i think it's a great project but if i click the info button i read the following:
```
"Instant Meshes is freely available under a BSD-style license. 
If you use the meshes obtained with this software, we kindly 
request that you acknowledge this and link to the project page at
http://igl.ethz.ch/projects/instant-meshes/"
```
Talking about the output as 3D model meshes  not always is possible to give the attribution of the output in particular when you work for a client.

In fact in all free and open source project like Blender, Gimp, Krita, Audacity,  we retain full copyright of the output ( 3D meshes, 2D images, Audio files ) and it's not necessary the attribution for the output.

If possible and practical, i agree that is nice to give the attribution also for the output too but as you wrote "kindly request" i interpret it as not mandatory, right? ( and i do not find this condition in the instant-meshes BSD-style 3-Clause license).

Thank you

**Comment by wjakob** [comment]
It's as the text says -- a request but not required.
