### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [wjakob/instant-meshes#8]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") like the following.
* [batch_process](https://github.com/OpenVSP/OpenVSP/blob/73d3e0f2e4326323036a6c7a3f63300882d99f91/src/geom_core/AdvLinkMgr.cpp#L35 "batch_process function")
* [Viewer](https://github.com/wjakob/instant-meshes/blob/9c85ba79f6676c6a5857b615b32c77167ea9e0f1/src/viewer.cpp#L630 "destructor for Viewer")

**Comment by wjakob** [comment]
The first link doesn't even refer to this project. If there are serious bugs please report them, but please refrain from posting super-minor stuff that just wastes everyone's time.

**Comment by elfring** [comment]
How do you think about to improve your software also by reuse of the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "a smart pointer")"?

Update candidates:
* [batch_process](https://github.com/wjakob/instant-meshes/blob/master/src/batch.cpp#L212 "batch_process function")
* [Viewer::loadState](https://github.com/wjakob/instant-meshes/blob/9c85ba79f6676c6a5857b615b32c77167ea9e0f1/src/viewer.cpp#L2110 "batch_process function")

**Comment by wjakob** [comment]
ditto..
