### ISSUE TITLE
Mac Binary

### ISSUE THREAD

**Issue by sn4fu** [wjakob/instant-meshes#81]
Hi,

I just downloaded MacOSX Binary of Instant Meshes from Github.

When I unzip the file there is a NO entry sign over the App indicating it won’t run.

I am on EL Capitan for various reasons, is this latest build Sierra only?

Thanks anyway amazing bit of software, had seen it used and wanted to try for myself .

regards

/t

**Comment by wjakob** [comment]
Sorry, can't reproduce -- it works fine here. We build using the latest toolchain on Travis, so there is a chance that your OSX is too outdated to work with the build. (You can always recompile yourself locally)

**Comment by sn4fu** [comment]
Thank you,

 I found an older version works fine . . .

/t

**Comment by artworks3d** [comment]
@sn4fu where did you find the version for Mac OS 10.11? I’m having no luck...

**Comment by vin-ni** [comment]
Would also be interested

**Comment by sn4fu** [comment]
Sorry, i just can’t remember where it came from , have updated all since . .
