### ISSUE TITLE
Want to save in different type of files!

### ISSUE THREAD

**Issue by breno159** [wjakob/instant-meshes#84]
Hi **wjakob**, first I want to thank you so much for this software! 
Its helped me a lot that you can't imagine haha
I had a lot of trouble trying to create surfaces for my meshes, and after searching a lot and test a lot of different software I found the Instant Meshes and was like a miracle! 
I was sooo happy to be able to create the surface in my models because I use **CNC machines** and Mastercam software to work in parts.. So is the combination of **meshmixer + instant meshes = mastercam (only for toolpaths).** 
but after I created the surface on the mesh, I notice that I can only export in 2 types of file.. and to make me more frustated, **MASTERCAM** don't read **.obj** and **.ply!** :/ 
I'm really need that software my friend! but I need to combine with mastercam :/ 
You think you can help me with this? creating different types of files like **.mcam , .mc** , even maybe **Autocad** files like **.dwg, .dxf, .dwf, .dwfx** 
Please man help me! :/ 
I'm stuck :/
I put the different types of files that mastercam can read! 
![screenshot_1](https://user-images.githubusercontent.com/21266098/45177199-4a2c2d80-b1e0-11e8-96d8-a6c4fbfb5334.jpg)

**Comment by BillDStrong** [comment]
You will want to use something like [MeshLab](http://www.meshlab.net) that allows you to convert between those formats. It is free and open source, and has lots of useful features for 3D Printing that are also useful for CNC Machining.

**Comment by PaddiM** [comment]
Meshmixer has an STL exporter and an OBJ importer. How export OBJ from Instant Meshes, read it inside Meshmixer and do an STL export?

**Comment by wjakob** [comment]
Closing, as this is not really an IM issue.
